---
bootstrap_node:
    name: bootstrap
    ip: 192.168.50.5
    mcaddr: 00:0d:b9:5f:ce:05

master_nodes:
    - name: master01
      ip: 192.168.50.10
      macaddr: 00:0d:b9:5f:ce:10

    - name: master02
      ip: 192.168.50.11
      macaddr: 00:0d:b9:5f:ce:11

    - name: master03 
      ip: 192.168.50.12
      macaddr: 00:0d:b9:5f:ce:12

worker_nodes:
    - name: worker01
      ip: 192.168.50.20
      macaddr: 00:0d:b9:5f:ce:20

    - name: worker02
      ip: 192.168.50.21
      macaddr: 00:0d:b9:5f:ce:21

    - name: worker03 
      ip: 192.168.50.22
      macaddr: 00:0d:b9:5f:ce:22


